# Generated by Django 3.2.12 on 2024-03-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boxGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groundName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('groundTime', models.CharField(choices=[('1', '8AM - 9AM'), ('2', '9AM - 10AM'), ('3', '10AM - 11AM'), ('4', '11AM - 12PM'), ('5', '3PM - 4PM'), ('6', '4PM - 5PM'), ('7', '6PM - 7PM'), ('8', '7PM - 8PM'), ('9', '9PM - 10PM'), ('10', '10PM - 11PM'), ('11', '11PM - 12AM'), ('12', '12AM - 1AM'), ('13', '1AM - 2AM')], max_length=20)),
                ('Price', models.IntegerField(default=600)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groundName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('Price', models.IntegerField(default=1500)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=50)),
                ('noOfOvers', models.IntegerField()),
                ('overPerBowler', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('ballType', models.CharField(choices=[('1', 'Tennis'), ('2', 'Leather'), ('3', 'Others')], max_length=30)),
                ('pitchType', models.CharField(choices=[('1', 'Rough'), ('2', 'Cement'), ('3', 'Turf'), ('4', 'AstroTurf'), ('5', 'Matting')], max_length=30)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.city')),
                ('ground_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.ground')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=25, unique=True)),
                ('Password', models.CharField(max_length=254)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contact_no', models.IntegerField()),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Batting_style', models.CharField(blank=True, max_length=20, null=True)),
                ('Bowling_style', models.CharField(blank=True, max_length=20, null=True)),
                ('Role', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImg', models.ImageField(upload_to='photos')),
                ('tournamentName', models.CharField(max_length=50)),
                ('organizerName', models.CharField(max_length=30)),
                ('organizerNum', models.DecimalField(decimal_places=0, max_digits=10)),
                ('organizerEmail', models.EmailField(max_length=254)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('tournamentCat', models.CharField(max_length=40)),
                ('ballType', models.CharField(choices=[('1', 'Tennis'), ('2', 'Leather'), ('3', 'Others')], max_length=30)),
                ('pitchType', models.CharField(choices=[('1', 'Rough'), ('2', 'Cement'), ('3', 'Turf'), ('4', 'AstroTurf'), ('5', 'Matting')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.city')),
                ('groundId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.ground')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(default='', max_length=50)),
                ('Captain_name', models.CharField(max_length=25)),
                ('Players', models.ManyToManyField(to='cricss.User')),
            ],
        ),
        migrations.CreateModel(
            name='ScorerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tossWin', models.CharField(max_length=30)),
                ('battingTeam', models.CharField(max_length=30)),
                ('bowlingTeam', models.CharField(max_length=30)),
                ('firstInnings_totalRuns', models.IntegerField()),
                ('firstInnings_totalFours', models.IntegerField()),
                ('firstInnings_totalSixs', models.IntegerField()),
                ('firstInnings_totalWicket', models.IntegerField()),
                ('secondInnings_totalRuns', models.IntegerField()),
                ('secondInnings_totalFours', models.IntegerField()),
                ('secondInnings_totalSixs', models.IntegerField()),
                ('secondInnings_totalWicket', models.IntegerField()),
                ('winnerTeam', models.CharField(max_length=30)),
                ('matchId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.match')),
                ('teamId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricss.team'),
        ),
    ]
