# Generated by Django 3.2.12 on 2024-03-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricss', '0002_auto_20240303_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_id2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='cricss.team'),
        ),
        migrations.AlterField(
            model_name='boxground',
            name='groundTime',
            field=models.CharField(choices=[('0', 'Select Time'), ('1', '8AM - 9AM'), ('2', '9AM - 10AM'), ('3', '10AM - 11AM'), ('4', '11AM - 12PM'), ('5', '3PM - 4PM'), ('6', '4PM - 5PM'), ('7', '6PM - 7PM'), ('8', '7PM - 8PM'), ('9', '9PM - 10PM'), ('10', '10PM - 11PM'), ('11', '11PM - 12AM'), ('12', '12AM - 1AM'), ('13', '1AM - 2AM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='ballType',
            field=models.CharField(choices=[('0', 'Select Ball Type'), ('1', 'Tennis'), ('2', 'Leather'), ('3', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='pitchType',
            field=models.CharField(choices=[('0', 'Select Pitch Type'), ('1', 'Rough'), ('2', 'Cement'), ('3', 'Turf'), ('4', 'AstroTurf'), ('5', 'Matting')], max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='cricss.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ballType',
            field=models.CharField(choices=[('0', 'Select Ball Type'), ('1', 'Tennis'), ('2', 'Leather'), ('3', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pitchType',
            field=models.CharField(choices=[('0', 'Select Pitch Type'), ('1', 'Rough'), ('2', 'Cement'), ('3', 'Turf'), ('4', 'AstroTurf'), ('5', 'Matting')], max_length=30),
        ),
    ]
