# Generated by Django 3.2.12 on 2024-03-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricss', '0005_auto_20240303_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscorerdetail',
            name='teamId',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bannerImg',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ManyToManyField(to='cricss.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricss.tournament')),
            ],
        ),
    ]
