# Generated by Django 3.2.12 on 2024-03-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricss', '0006_auto_20240324_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='bannerImg',
        ),
    ]
