# Generated by Django 3.2.12 on 2024-04-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricss', '0010_scorecard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentTeam',
        ),
    ]
