# Generated by Django 3.2.12 on 2024-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricss', '0013_tourteam_captain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxground',
            name='organizername',
            field=models.CharField(default='', max_length=25),
        ),
    ]
