# Generated by Django 3.2.12 on 2024-04-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricss', '0015_auto_20240410_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricss.boxground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricss.user')),
            ],
        ),
    ]
